# Generated by Django 4.0.3 on 2022-03-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0002_delete_colour_delete_cutting_delete_highlights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cutting & Styling',
                'verbose_name_plural': 'Cutting & Styling',
            },
        ),
    ]
